apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mysqldb-backup
  annotations:
    description: "Template for MySQL container backup job"
    tags: "database,MySQL,backup"
  labels:
    appcluster: nextcloud
parameters:
- name: BACKUP_SCHEDULE
  description: "Cron-like schedule expression. Default: Every day at 22:39'"
  value: '39 15 * * *'
- name: BACKUP_KEEP
  description: "Number of backups to keep"
  value: "7"
- name: tools_namespace
  description: namespace for tools (Source for local MySQL ImagesStream)
  required: true
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: mysqldb-backup
    labels:
      appcluster: nextcloud
  spec:
    schedule: '${BACKUP_SCHEDULE}'
    concurrencyPolicy: Forbid
    jobTemplate:
      spec:
        template:
          spec:
            volumes:
              - name: mysql-backup-data
                persistentVolumeClaim:
                  claimName: mysql-backups
            containers:
              - name: mysql-backup
                image: image-registry.openshift-image-registry.svc:5000/${tools_namespace}/mysql
                command:
                  - bash
                  - -c
                  - DATE=$(date +%Y%m%d-%H-%M-%S); ls -rdt1 /var/lib/mysql/data/mysql-* |
                    head -n -$BACKUP_KEEP | xargs rm;
                    /usr/bin/mysqldump --skip-lock-tables -h http://mysql -P 3306 -u root --password=$MYSQL_ROOT_PASSWORD --all-databases > /var/lib/mysql/backups/mysql-$DATE.sql;
                env:
                - name: BACKUP_KEEP
                  value: ${BACKUP_KEEP}
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: mysql
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-root-password
                      name: mysql
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: mysql
                volumeMounts:
                  - name: mysql-backup-data
                    mountPath: /var/lib/mysql/backups
            restartPolicy: Never
