kind: Template
apiVersion: v1
metadata:
  name: mysql-installer
  annotations:
    description: "Mysql - A safe home for all your data"
    tags: "fileshare,nextcloud"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "JAG-MYSQL"
    template.openshift.io/documentation-url: "https://github.com/bcgov/jag-csbnextcloud.git"
    template.openshift.io/support-url: "https://github.com/bcgov/jag-csbnextcloud/issues"
parameters:
- name: tools_namespace
  description: OpenShift Namespace of ImageStreams
  required: true
- description: Maximum amount of memory the db container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 8Gi
- description: Requested amount of memory the db container can use.
  displayName: Memory Limit
  name: MEMORY_REQUEST
  required: true
  value: 4Gi
- description: Maximum amount of cpu the db container can use.
  displayName: Memory Limit
  name: CPU_LIMIT
  required: true
  value: '1'
- description: Requested amount of cpu the db container can use.
  displayName: Memory Limit
  name: CPU_REQUEST
  required: true
  value: 500m
- description: The name of the OpenShift Service exposed for the database.
  displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: mysql
- description: Username for mysql user that will be used for accessing the database.
  displayName: mysql Connection Username
  from: user[A-Z0-9]{3}
  generate: expression
  name: MYSQL_USER
  required: true
- description: Password for the mysql connection user.
  displayName: mysql Connection Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_PASSWORD
  required: true
- description: Password for the mysql root user.
  displayName: mysql root Password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: MYSQL_ROOT_PASSWORD
  required: true
- description: Name of the MySQL database accessed.
  displayName: MySQL Database Name
  name: MYSQL_DATABASE
  required: true
  value: mysql
- description: Version of mysql image to be used (10.1, 10.2 or latest).
  displayName: Version of mysql Image
  name: DB_VERSION
  required: true
  value: latest
- description: Volume space available for mysql data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 4Gi

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-MYSQL_DATABASE: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: ${DATABASE_SERVICE_NAME}
    labels:
      appcluster: nextcloud-mysql
  stringData:
    database-name: ${MYSQL_DATABASE}
    database-password: ${MYSQL_PASSWORD}
    database-root-password: ${MYSQL_ROOT_PASSWORD}
    database-user: ${MYSQL_USER}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
    name: ${DATABASE_SERVICE_NAME}
    labels:
      appcluster: nextcloud-mysql
  spec:
    ports:
    - name: mysql
      port: 3306
    selector:
      name: ${DATABASE_SERVICE_NAME}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${DATABASE_SERVICE_NAME}
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-block-standard
    labels:
      appcluster: nextcloud-mysql
  spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: netapp-block-standard
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${DATABASE_SERVICE_NAME}-backups
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-file-standard
    labels:
      appcluster: nextcloud-mysql
  spec:
    accessModes:
    - ReadWriteMany
    storageClassName: netapp-file-standard
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${DATABASE_SERVICE_NAME}
    labels:
      appcluster: nextcloud-mysql
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-root-password
                name: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database-name
                name: mysql
          image: mysql:${DB_VERSION}
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mysql
          ports:
          - containerPort: 3306
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
              cpu:  ${CPU_LIMIT}
            requests:
              memory: ${MEMORY_REQUEST}
              cpu:  ${CPU_REQUEST}
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: ${DATABASE_SERVICE_NAME}-data
          - mountPath: /var/lib/backups
            name: ${DATABASE_SERVICE_NAME}-backups
          - name: config-mount
            mountPath: /etc/mysql/my.cnf
            subPath: my.cnf
        volumes:
        - name: ${DATABASE_SERVICE_NAME}-data
          persistentVolumeClaim:
            claimName: ${DATABASE_SERVICE_NAME}
        - name: ${DATABASE_SERVICE_NAME}-backups
          persistentVolumeClaim:
            claimName: ${DATABASE_SERVICE_NAME}-backups
        - name: config-mount
          configMap:
            name: my.cnf
            defaultMode: 420
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mysql
        from:
          kind: ImageStreamTag
          name: mysql:${DB_VERSION}
          namespace: ${tools_namespace}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my.cnf
  data:
    my.cnf: |-
        # Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.
        #
        # This program is free software; you can redistribute it and/or modify
        # it under the terms of the GNU General Public License as published by
        # the Free Software Foundation; version 2 of the License.
        #
        # This program is distributed in the hope that it will be useful,
        # but WITHOUT ANY WARRANTY; without even the implied warranty of
        # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        # GNU General Public License for more details.
        #
        # You should have received a copy of the GNU General Public License
        # along with this program; if not, write to the Free Software
        # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

        #
        # The MySQL  Server configuration file.
        #
        # For explanations see
        # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

        [server]
        skip_name_resolve = 1
        innodb_buffer_pool_size = 3G
        innodb_buffer_pool_instances = 1
        innodb_io_capacity = 12
        innodb_flush_log_at_trx_commit = 1
        innodb_log_buffer_size = 32M
        innodb_max_dirty_pages_pct = 90
        tmp_table_size= 64M
        max_heap_table_size= 64M
        log-error=/var/lib/mysql/mysql.err


        # Enable the below for troubleshooting query performance
        #slow_query_log = 1
        #slow_query_log_file = /var/log/mysql/slow.log
        #long_query_time = 1


        [client]
        default-character-set = utf8mb4

        [mysqld]
        pid-file        = /var/run/mysqld/mysqld.pid
        socket          = /var/run/mysqld/mysqld.sock
        datadir         = /var/lib/mysql
        #query_cache_type = 1
        #query_cache_limit = 2M
        #query_cache_min_res_unit = 2k
        #query_cache_size = 64M
        secure-file-priv= NULL
        character_set_server = utf8mb4
        collation_server = utf8mb4_general_ci
        transaction_isolation = READ-COMMITTED
        binlog_format = ROW
        binlog_expire_logs_seconds = 172800 #2 days
        #innodb_large_prefix=on
        #innodb_file_format=barracuda
        #innodb_file_per_table=1
        max_connections = 200

        # Custom config should go here
        !includedir /etc/mysql/conf.d/
