kind: Template
apiVersion: v1
metadata:
  name: nextcloud
  annotations:
    description: "Nextcloud Builder - takes a source dockerimage and dockerfile to create a custom container"
    tags: "fileshare,nextcloud"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "ChrisHoban"
    template.openshift.io/documentation-url: "https://github.com/bcgov/jag-csbnextcloud"
    template.openshift.io/support-url: "https://github.com/bcgov/jag-csbnextcloud/issues"
parameters:
- name: MY_NEXTCLOUD_DOCKERFILE_REPO
  description: Nginx Dockerfile source repository
  value: https://github.com/bcgov/jag-csbnextcloud.git
- name: MY_NEXTCLOUD_DOCKERFILE_REPO_REF
  description: Nginx Dockerfile source repository branch / tags
  value: main
- name: MY_NEXTCLOUD_CONTEXT_DIR
  description: Nextcloud Context Directory
  value:
- name: namespace
  description: Namespace containing nextcloud imagestreams
  value:
- name: outputImageName
  required: true
  description: output imagestream
- name: imageTag
  description: output tag
  required: true
objects:
- kind: BuildConfig
  apiVersion: v1
  namespace: {namespace}
  metadata:
    creationTimestamp: null
    labels:
      build: ${outputImageName}
      app: nextcloud
      appcluster: nextcloud
    name: ${outputImageName}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${outputImageName}:{imageTag}
        namespace: ${namespace}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${MY_NEXTCLOUD_DOCKERFILE_REPO}
        ref: ${MY_NEXTCLOUD_DOCKERFILE_REPO_REF}
      type: Git
      contextDir: ${MY_NEXTCLOUD_CONTEXT_DIR}
    strategy:
      dockerStrategy:
        imageOptimizationPolicy: SkipLayers
        from:
          kind: ImageStreamTag
          name: nextcloud:{imageTag}
      type: Docker
    triggers:
    - type: ConfigChange
