kind: Template
apiVersion: v1
metadata:
  name: mysql-installer
  annotations:
    description: "Mysql - A safe home for all your data"
    tags: "fileshare,nextcloud"
    iconClass: fa-cloud-upload
    template.openshift.io/provider-display-name: "JAG-NEXTCLOUD"
    template.openshift.io/documentation-url: "https://github.com/bcgov/jag-csbnextcloud.git"
    template.openshift.io/support-url: "https://github.com/bcgov/jag-csbnextcloud/issues"
parameters:
- description: Nextcloud Service Name
  displayName: Nextcloud Service Name
  name: nextcloud_name
  required: true
  value: nextcloud
- name: CURL_URL
  description: "Curl URL to hit  (eg: 'http://servicename/uri' )"
  required: true
  value: 'http://servicename/cron.php'
- name: SCHEDULE
  description: "Schedule of cron  (eg: '*/15 * * * *' every 15 minutes)"
  required: true
  value: '*/5 * * * *'
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${nextcloud_name}-webcron
    labels:
      appcluster: ${nextcloud_name}
  spec:
    schedule: ${SCHEDULE}
    startingDeadlineSeconds: 200
    concurrencyPolicy: Replace
    suspend: false
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
            labels:
              name: ${nextcloud_name}-job
              parent: ${nextcloud_name}-cronjob
          spec:
            containers:
              - name: ${nextcloud_name}-job-pod
                image: >-
                  image-registry.openshift-image-registry.svc:5000/openshift/httpd@sha256:b21e28894aab0a576079a8482a18a1d3ac73c63aad0647258651c9739a3e33f9
                command:
                  - /bin/sh
                args:
                  - '-c'
                  - >-
                    curl -XPOST
                    '${CURL_URL}'
                    --header 'Content-Type: application/json' --header
                    'Transfer-encoding: chunked' -d ""
                resources: {}
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
                imagePullPolicy: IfNotPresent
            restartPolicy: OnFailure
            terminationGracePeriodSeconds: 30
            dnsPolicy: ClusterFirst
            securityContext: {}
            schedulerName: default-scheduler
    successfulJobsHistoryLimit: 3
    failedJobsHistoryLimit: 1
